name: alevin
description: Quantification of single cell data with Salmon Alevin
keywords:
    - alevin
    - salmon
    - single cell
    - alignment
    - map
    - fastq
tools:
    - salmon:
        description: |
            Alevin is a tool — integrated with the salmon software — that introduces a family of algorithms 
            for quantification and analysis of 3’ tagged-end single-cell sequencing data. 
            Currently alevin supports the following two major droplet based single-cell protocols:
              Drop-seq
              10x-Chromium v1/2/3
        homepage: https://salmon.readthedocs.io/en/latest/alevin.html
        documentation: https://salmon.readthedocs.io/en/latest/alevin.html
        doi: "doi.org/10.1186/s13059-019-1670-y"
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
            List of input FastQ files of size 2 for paired-end data.
    - index:
        type: file
        description: Salmon genome index files
        pattern: "Directory containing Salmon index *.{amb,ann,bwt,pac,sa}"
    - txp2gene:
        type: file
        description: Transcript to genes mapping file
        pattern: "File containing a map of transcript to genes *.{txt,tsv}"
    - protocol:
        type: value
        description: Protocol used to generate the data
    - whitelist:
        type: file
        description: Whilelist barcodes file
        pattern: "File containing the barcodes *.{txt,tsv}"
output:
    - alevin_results:
        type: file
        description: Output folder file containing quantification
        pattern: "*.{_alevin_results}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@jfnvarro"
    - "@XXX"
