name: alevinfry_index
description: Build a salmon index of a splici reference.
    - index
    - fasta
    - genome
    - reference
tools:
    - salmon:
        description: |
          Salmon is a tool for wicked-fast transcript quantification from RNA-seq data
        homepage: https://salmon.readthedocs.io/en/latest/salmon.html
        manual: https://salmon.readthedocs.io/en/latest/salmon.html
        doi: 10.1038/nmeth.4197
input:
    - splici_transcriptome:
        type: file
        description: |
          Fasta file of the splici (Spliced + Intron) transcriptome.

output:
    - index:
      type: directory
      description: Directory containing the alevinfry index
      pattern: "alevinfry"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"

authors:
  - "@fbdtemme"
  - "@jfnavarro"
