name: alignsolo
description: Align reads to a reference genome using STARSolo
keywords:
  - align
  - fasta
  - genome
  - reference
  - single cell
tools:
  - star:
      description: |
        STAR is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome. STARsolo is the
        version that is compatible with single cell data.
      homepage: https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md
      manual: https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
      doi: 10.1093/bioinformatics/bts635
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test']
  - reads:
      type: file
      description: |
        List of input FastQ files respectively.
  - index:
      type: directory
      description: STAR genome index
      pattern: "star"
  - whilelist:
      type: file
      description: A file with the barcodes
  - protocol:
      type: value
      description: Single cell protocol used
output:
  - bam:
      type: file
      description: Output BAM file containing read alignments
      pattern: "*.{bam}"
  - log_final:
      type: file
      description: STAR final log file
      pattern: "*Log.final.out"
  - log_out:
      type: file
      description: STAR lot out file
      pattern: "*Log.out"
  - log_progress:
      type: file
      description: STAR log progress file
      pattern: "*Log.progress.out"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - bam_sorted:
      type: file
      description: Sorted BAM file of read alignments (optional)
      pattern: "*sortedByCoord.out.bam"
  - bam_transcript:
      type: file
      description: Output BAM file of transcriptome alignment (optional)
      pattern: "*toTranscriptome.out.bam"
  - bam_unsorted:
      type: file
      description: Unsorted BAM file of read alignments (optional)
      pattern: "*Aligned.unsort.out.bam"
  - fastq:
      type: file
      description: Unmapped FastQ files (optional)
      pattern: "*fastq.gz"
  - tab:
      type: file
      description: STAR output tab file(s) (optional)
      pattern: "*.tab"

authors:
    - "@jfnvarro"
    - "@XXX"