name: alevinqc
description: Computationa of QC stats from Salmon Alevin
keywords:
    - alevin
    - salmon
    - single cell
    - qc
    - stats
tools:
    - salmon:
        description: |
            Alevin is a tool — integrated with the salmon software — that introduces a family of algorithms 
            for quantification and analysis of 3’ tagged-end single-cell sequencing data. 
            Currently alevin supports the following two major droplet based single-cell protocols:
              Drop-seq
              10x-Chromium v1/2/3
        homepage: https://salmon.readthedocs.io/en/latest/alevin.html
        documentation: https://salmon.readthedocs.io/en/latest/alevin.html
        doi: "doi.org/10.1186/s13059-019-1670-y"
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
    - alevin_results:
        type: file
        description: |
            Path to the results from Salmon Alevin.
output:
    - report:
        type: file
        description: Output folder file containing the QC report
        pattern: "*.{alevinReport.html}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@jfnvarro"
    - "@XXX"
