name: cellranger_getreferences
description: Download and unpack cellranger reference genomes from the 10X website.
keywords: 
    - genome
    - cellranger
    - reference

tools:
    - cellranger:
        description: |
            Cell Ranger is a set of analysis pipelines that process Chromium single-cell data to align reads,
            generate feature-barcode matrices, perform clustering and other secondary analysis, and more. 
input:
    - genome:
        type: string
        description: |
            Name of the reference to fetch. Supported values: GRCh38, mm10

output:
    - reference:
        type: directory
        description: |
            Directory containiner cellranger reference files
