name: gffread
description: Validate, filter, convert and perform various other operations on GFF files
keywords:
  - gff
  - conversion
  - validation
tools:
  - gffread:
      description: GFF/GTF utility providing format conversions, region filtering, FASTA sequence extraction and more.
      homepage: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread
      documentation: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread
      tool_dev_url: https://github.com/gpertea/gffread
      doi: 10.12688/f1000research.23297.1
      licence: ['MIT']

input:
  - genome_fasta:
        type: file
        description: A reference genome in FASTA format.
        patter: "*.fasta"
  - gff:
        type: file
        description: A reference file in either the GFF3, GFF2 or GTF format.
        patter: "*.{gff, gtf}"

output:
  - transcriptome_extracted:
      type: file
      description: The resulting transcriptome reference file in FASTA format.
      pattern: "*.transcriptome.fa"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
    - "@jfnvarro"
    - "@XXX"
