name: generate_permitlist
description:  Determines what cell barcodes should be associated with “true” cells, which should be corrected, and which should be ignored.
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - alevinfry_generate_permitlist:
        description: |
            alevin-fry is a suite of tools for the rapid, accurate and memory-frugal processing single-cell and single-nucleus sequencing data.
        homepage: https://github.com/COMBINE-lab/alevinfry
        manual: https://alevin-fry.readthedocs.io/en/latest/
        doi: 10.1101/2021.06.29.450377v1
input:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - map:
        type: directory
        description: |
          A directory that contains a mapping RAD file (created by running alevin with the --rad and/or --sketch flags).
    - expected_orientation:
        type: value
        description: |
          The expected orientation of properly mapped reads. Possible values: fw, rc or both.

output:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: directory
        description: |
          A directory that contains the various output files.
          The file all_freq.tsv is a two-column tab-separated file that lists, for each distinct barcode in the input RAD file, the number of read records that were tagged with this barcode.
          The file permit_freq.tsv is a two-column tab-separated file that lists, for each barcode in the input RAD file that is determined to be a true barcode, the number of read records associated with this barcode.
          The file permit_map.bin is a binary file (a serde serialized HashMap) that maps each barcode in the input RAD file that is within an edit distance of 1 to some true barcode to the barcode to which it corrects. 
          This allows the collate command to group together all of the read records corresponding to the same corrected barcode.
          The file generate_permit_list.json that is a JSON file containing information about the run of the command (currently, just the expected orientation).
        pattern: ".*{_alevinfry_quant}"

    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"

authors:
  - "@fbdtemme"
  - "@jfnavarro"