name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS full tests
    if: github.repository == 'nf-core/scrnaseq'
    runs-on: ubuntu-latest
    # Do a full-scale run with each of the tools
    strategy:
      matrix:
        tools: ["star", "alevin", "kallisto", "alevinfry"]
    steps:
      - name: Launch workflow via tower
        uses: nf-core/tower-action@master
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          bearer_token: ${{ secrets.TOWER_BEARER_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          pipeline: ${{ github.repository }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/scrnaseq/work-${{ github.sha }}
          parameters: |
            {
              "outdir" : "s3://${{ secrets.AWS_S3_BUCKET }}/scrnaseq/results-${{ github.sha }}/aligner_${{ matrix.tools }}",
              "aligner": "${{ matrix.tools }}"
            }
          profiles: '[ "test_full", "aws_tower" ]'